In [1]:
import numpy as np

In [2]:
arr = np.array([1,1,1,2,3,2,4,5,7,1,4,2])

In [5]:
x4 = np.where(arr == 1)

In [6]:
x4

(array([0, 1, 2, 9], dtype=int64),)

In [7]:
arr[x4]

array([1, 1, 1, 1])

In [8]:
even = np.where(arr%2 == 0)
arr[even]

array([2, 2, 4, 4, 2])

In [9]:
np.sort(arr)

array([1, 1, 1, 1, 2, 2, 2, 3, 4, 4, 5, 7])

In [10]:
np.sort(arr)[::-1]

array([7, 5, 4, 4, 3, 2, 2, 2, 1, 1, 1, 1])

In [11]:
s= np.array(['aaa','aa','b','a','ba','ab','bb'])

In [14]:
s[np.where(s < 'b')]

array(['aaa', 'aa', 'a', 'ab'], dtype='<U3')

In [15]:
np.sort(s)

array(['a', 'aa', 'aaa', 'ab', 'b', 'ba', 'bb'], dtype='<U3')

In [16]:
np.sort(s)[::-1]

array(['bb', 'ba', 'b', 'ab', 'aaa', 'aa', 'a'], dtype='<U3')

In [21]:
arr = np.array([41,42,43,50,56])
filter_arr = [0,1,0,1,1]
arr[filter_arr == np.ones(5)]

array([42, 50, 56])

In [24]:

arr = np.array([41,42,43,50,56])
filter_arr =[False,  True, False,  True,  True]
arr[filter_arr ]

array([42, 50, 56])

In [26]:
filter_arr.clear()
fliter_arr = [] 
for x in arr: 
    if(x > 43):
        filter_arr.append(True)
    else: 
        filter_arr.append(False)
filter_arr  


[False, False, False, True, True]

In [27]:
arr[filter_arr]

array([50, 56])

In [39]:
# filter_arr.clear()
arr = np.array([1,2,3,4,5,6,7,8,9,10])
far = arr % 2 == 0
far

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [40]:
arr[far]

array([ 2,  4,  6,  8, 10])

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])