In [1]:
pip list

Package                           Version
--------------------------------- ------------------
aext-assistant                    4.20.0
aext-assistant-server             4.20.0
aext-core                         4.20.0
aext-core-server                  4.20.0
aext_environments_server          4.20.0
aext-panels                       4.20.0
aext-panels-server                4.20.0
aext-project-filebrowser-server   4.20.0
aext-share-notebook               4.20.0
aext-share-notebook-server        4.20.0
aext-shared                       4.20.0
aext-toolbox                      4.20.0
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
alembic                           1.13.3
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-auth                     0.8.6
anaconda-

In [2]:
import numpy as np

In [3]:
arr  = np.array([1,2,3,4,6])
print(arr)
print(type(arr))

[1 2 3 4 6]
<class 'numpy.ndarray'>


In [14]:
a = np.array(42)
b = np.array([1,2,3])
c= np.array([[12,3,4],[5,3,7]])
d = np.array([ [ [4,5,6,7],[74,2,8,6]] , [ [7,8,9 ,7 ] ,[4, 7, 9, 8] ] ])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
arr = np.array([1,2,3,4,5])
print(arr[1]+arr[-1])

7


In [16]:
arr  = np.array([[1,2,3],[7,8,9]])
print(arr[1,1])

8


In [17]:
arr= np.array([ [[1,2,3],[7,8,9]],[ [7,4,1],[8,5,2]] ])
print(arr[1,1,0])

8


In [18]:
arr[-1]

array([[7, 4, 1],
       [8, 5, 2]])

In [19]:
arr[-1,-1,-1]

2

In [20]:
arr = np.array([ [1,2,3,4,5,6,7,8,9],[9,8,7,4,1,5,2,6,3]])

In [21]:
arr[0,0:2]

array([1, 2])

In [22]:
arr[1,1:3]

array([8, 7])

In [23]:
arr = np.array([ 1,2,3,4,5,6,7,8,9])

In [24]:
arr[0:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[-3:-1:1]

array([7, 8])

In [31]:
arr[1:2]

array([2])

In [32]:
arr[:2]

array([1, 2])

In [33]:
arr[1:3]

array([2, 3])

In [34]:
arr[0::2]

array([1, 3, 5, 7, 9])

In [35]:
arr = np.array([ [1,2,3,4,5,6,7,8,9],[9,8,7,4,1,5,2,6,3]])


In [36]:
arr[1]

array([9, 8, 7, 4, 1, 5, 2, 6, 3])

In [39]:
arr[0:2,1::2]

array([[2, 4, 6, 8],
       [8, 4, 5, 6]])

In [41]:
arr = np.array([1,2,3,4,5,])

In [42]:
for x in arr: 
    print(x)

1
2
3
4
5


In [43]:
arr = np.array([ [1,2,3,4,5,6,7,8,9],[9,8,7,4,1,5,2,6,3]])

In [44]:
for x in arr: 
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
9
8
7
4
1
5
2
6
3


In [ ]:
for x in arr.nditer()